Repository jcklie/anki-maobi, pull requests merged in 2020-03, with the labels that each got.

#29 #28 - restarting quizzes
  README.md
  maobi/quiz.js
  maobi/quiz.py
Labels: Module: Javascript

#31 #30 - Use new 2.1.20 hook
  maobi/__init__.py
Labels: Critical, 🐛Bug

#34 #33 - Improve maobi night mode
  maobi/quiz.js
Labels: Module: Javascript, 🆕Enhancement
