Repository jcklie/anki-maobi, pull requests merged in 2020-01, with the labels that each got.

#22 #5 - Quizzes with multiple characters
  .gitignore
  README.md
  img/maobi_multiple.gif
  maobi/__version__.py
  maobi/config.py
  maobi/hanzi-writer.min.js
  maobi/quiz.js
  maobi/quiz.py
  scripts/package.py
Labels: Module: Hanzi Writer, Module: Javascript, 🆕Enhancement

#23 #14 - add more configuration options
  README.md
  maobi/config.py
  maobi/quiz.js
  maobi/quiz.py
Labels: Module: Qt, 🆕Enhancement

#24 #21 - reveal character
  README.md
  maobi/quiz.js
  maobi/quiz.py
Labels: Module: Javascript, 🆕Enhancement

#26 #25 - Add more contributing information
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  CONTRIBUTING.md
  CONTRIBUTORS.txt
  README.md
Labels: Documentation

#27 #20 - Make it work on Mobile
  README.md
Labels: Documentation
